name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar o Poetry
        run: |
            curl -sSL https://install.python-poetry.org | python3 -
            echo "$HOME/.local/bin" >> $GITHUB_PATH

            - name: Configurar cache do Poetry
            uses: actions/cache@v3
            with:
              path: |
                ~/.cache/pypoetry
                ~/.cache/pip
              key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
              restore-keys: |
                poetry-${{ runner.os }}-
          